__title__ = "mbapy"
__description__ = "MyBA in Python"
__url__ = "https://github.com/BHM-Bob/BA_PY"
__version__ = "0.0.2"
__author__ = "BHM-Bob G"
__author_email__ = "bhmfly@foxmail.com"
__license__ = "MIT"